application: dbutils
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /my/.*
  script: main.py
  login: required
  
- url: .*
  script: main.py
